### ISSUE TITLE
[BUG] Incompatibility with CUB

### ISSUE THREAD

**Issue by 9ryex5** [TabletopsAndAnvils/Foundry-Stream-Module#3]
This is a strange one.
Having FSM enabled causes this error when trying to open Condition Lab from [CUB](https://foundryvtt.com/packages/combat-utility-belt/):

![image](https://user-images.githubusercontent.com/43207603/106850966-55cff700-66ad-11eb-9f9d-1e5030431a2f.png)

**Comment by TabletopsAndAnvils** [comment]
That is really strange, especially since they have nothing in common. FSM is strictly what I would consider 'back of the house' in operation, doesn't touch any db files or game information at all outside of it's own configuration and a quick peak at the chat message cards as they get created. Aside from that is pretty much playing by itself. I'm going to see if I can recreate that.

**Comment by TabletopsAndAnvils** [comment]
I did a little research. First, I was able to use CUB and it's Conditions Lab without any errors. Second, after a little searching you're not the only one to have had this issue, however I only found issues from before FSM was released to the public dating back to 09/29/20 - I also searched CUB's known issues and do not see it there. I'm in a channel with errational, so I'll reach out to him to do a little more digging. Did you get a specific indication in the dev console that would point to FSM or even to CUB? The only issue that I found regarding this particular error that even had a speculation as to why it happened seems to indicate that it may be do to an error while Foundry was compressing/cleaning up part of the NeDB databases, in that instance it was users.db. Any more insight you could give would be great.

**Comment by 9ryex5** [comment]
I could reproduce thisin Release 0.2.1 just by creating a new world, enabling CUB and FSM and trying to open Condition Lab. I was getting these errors in console: 
![image](https://user-images.githubusercontent.com/43207603/106983357-aa32af80-675d-11eb-9624-65c30d21eea4.png)

However after updating FSM to Release 0.2.2r this is not happening anymore :)

**Comment by TabletopsAndAnvils** [comment]
Well then, looks like we can close it! That tmi.min.js error will keep on popping up if it doesn’t register your nick on the first go around, there’s two others I see as well, but they aren’t anything to worry about it’s just the module being impatient on init. There’s another that pops up about include, but again it just wants to jump the gun every time it’s loading. After the first cycle it’s good to go. Still, I’m going to ask around, learn what I can just do it isn’t repeated in the future. Enjoy 0.2.2r!
