### ISSUE TITLE
[BUG] Disabling receiving from Twitch problem

### ISSUE THREAD

**Issue by 9ryex5** [TabletopsAndAnvils/Foundry-Stream-Module#4]
With these settings I keep receiving messages from twitch:
![image](https://user-images.githubusercontent.com/43207603/106851150-a47d9100-66ad-11eb-8257-b25335ff0dce.png)

**Comment by TabletopsAndAnvils** [comment]
Working on it right now, should be pushing an update here in a little bit!

**Comment by TabletopsAndAnvils** [comment]
0.2.2r has just been pushed and addressed that issue! Update should also auto-obfuscate your OAuth token, some streamers were requesting it. If you have an issue with the automatic update, ie it fails to connect, please let me know so I can address it. All of my servers have been updated manually so I kind of wrote the code blind. :) The simple way to fix it is to enter a random value into your OAuth configuration, save, open config again and copy/paste the actual OAuth token. From then on it will do it's thing as it should!
