### ISSUE TITLE
cover image is incorrect

### ISSUE THREAD

**Issue by kakaroto** [TabletopsAndAnvils/Foundry-Stream-Module#5]
The cover media in the module.json points to https://github.com/TabletopsAndAnvils/Foundry-Stream-Module/blob/main/img/fsm-cover.png which is an html page.
It should point to https://raw.githubusercontent.com/TabletopsAndAnvils/Foundry-Stream-Module/main/img/fsm-cover.png

**Comment by TabletopsAndAnvils** [comment]
Thanks, corrected the issue in 0.2.3
