### ISSUE TITLE
[BUG] Legacy View disables chat messages

### ISSUE THREAD

**Issue by 9ryex5** [TabletopsAndAnvils/Foundry-Stream-Module#8]
When Legacy View from FSM is enabled, text messages are not displayed in chat.

![image](https://user-images.githubusercontent.com/43207603/121015791-4a8ff380-c793-11eb-8f12-59909ce71030.png)

**Comment by TabletopsAndAnvils** [comment]
> When Legacy View from FSM is enabled, text messages are not displayed in chat.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/43207603/121015791-4a8ff380-c793-11eb-8f12-59909ce71030.png)
> 
> 

What version of Foundry are you running?

**Comment by 9ryex5** [comment]
0.8.6
